version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic


    steps:
      - checkout

      - run:
          name: Setup prereqs
          command: |
              apt-get update
              apt-get install -y build-essential wget unzip unrar-free texinfo git openjdk-8-jdk dos2unix

      - run:
          name: build toolchain
          command: make toolchain_build

      - run:
          name: build tools
          command: make tools_build

      - run:
          name: build SGDK
          command: sgdk_build
